### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sdsanches** [parse-community/Parse-SDK-iOS-OSX#1159]
When executing the project **"ParseStarterProject" v.1.15.0**, in **Xcode 8.2.1** I receive the error below:

![captura de tela 2017-07-13 as 16 01 07](https://user-images.githubusercontent.com/2859891/28183081-8a83bd4a-67e4-11e7-8bd8-2be67d38a1b1.png)

When I add the `Parse.framework `and `Bolts.framework` libraries to an existing project, I get the same error.

1. Do I need to do any additional configuration to be able to compile?
2. Any possible solution to the case?

**Comment by camcelroy** [comment]
I am seeing this as well.  If this is holding you up, using the 1.15.0 starter project while pulling in the Parse.framework from the 1.14.4 release will successfully build.  The issue appears to have started with the 1.14.5 release.  I have not yet parsed through the diffs between those releases, though I suspect someone with more knowledge of the project may be able to do that more efficiently.

**Comment by ColossalChris** [comment]
Had the same issue as well trying to run anything from 1.14.5 on, but .3 is working for me

**Comment by nebitrams** [comment]
I am using Xcode 8.3.2 and tried the followings.

Parse-iOS-1.15.0 : hit the same "___llvm_profile_runtime" undefined symbol error
Parse-iOS-1.14.5 : hit the same "___llvm_profile_runtime" undefined symbol error
Parse-iOS-1.14.4 : works fine.

As Xcode 8.3.3 was released on 6-Jun-2017 and the two newer Parse iOS releases are at end of June.  Is there any chance that the 1.14.5 onwards requires the latest Xcode 8.3.3?

For now, I am using 1.14.4 with Xcode 8.3.2.  I will try to download Xcode 8.3.3 to see whether 1.15.0 works along with it.

**Comment by flovilmart** [comment]
probably because I built manually those releases with incompatible Xcode versions.

**Comment by ceramicatheist** [comment]
This seems to have returned with the 1.15.3 build? (which includes Bolts 1.8.4)
```
Undefined symbols for architecture arm64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Parse(PFWeakValue.o)
      ___llvm_profile_runtime_user in Parse(PFUserState.o)
      ___llvm_profile_runtime_user in Parse(PFCommandURLRequestConstructor.o)
      ___llvm_profile_runtime_user in Parse(PFCoreManager.o)
      ___llvm_profile_runtime_user in Parse(PFURLSessionUploadTaskDelegate.o)
      ___llvm_profile_runtime_user in Parse(PFPin.o)
      ___llvm_profile_runtime_user in Parse(PFMulticastDelegate.o)
      ...
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Happens both when using the downloadable frameworks, and when building them manually with Xcode Version 9.0 (9A235)

**Comment by airdrummingfool** [comment]
I'm also having this issue with 1.15.3 in Xcode 9.0 9A235. I've only tried the prebuilt framework from the Github releases page.

**Comment by decoyfox** [comment]
I am also having this issue:

`Undefined symbols for architecture arm64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Parse(PFCloud.o)
      ___llvm_profile_runtime_user in Parse(PFFile.o)
      ___llvm_profile_runtime_user in Parse(PFGeoPoint.o)
      ___llvm_profile_runtime_user in Parse(PFInstallation.o)
      ___llvm_profile_runtime_user in Parse(PFObject.o)
      ___llvm_profile_runtime_user in Parse(PFQuery.o)
      ___llvm_profile_runtime_user in Parse(PFUser.o)
      ...
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Xcode: Version 9.0 (9A235)
Parse SDK 1.15.3

**Comment by flovilmart** [comment]
I’ll have a look m, again.

**Comment by decoyfox** [comment]
My project also builds fine with 1.15.2, as @airdrummingfool mentioned above.

**Comment by flovilmart** [comment]
I used the exact same command for both, perhaps it has to do with some compile flags added when moving to Xcode 9 recommended settings

**Comment by decoyfox** [comment]
Let me know if I can help you troubleshoot in any way.

**Comment by flovilmart** [comment]
JuSt checked the diff and besides additional warnings, it doesn’t seem we’ve added more build settings. I used the `rake package:frameworks` as usual. Can you try the same and see if the produced frameworks are functional?

**Comment by decoyfox** [comment]
@flovilmart sorry, I'm not too well versed in these commands. my "help" might be more of an impediment ¯\_(ツ)_/¯

**Comment by flovilmart** [comment]
Step by step:

1- clone the repo
2- in the folder: 
- gem install bundler
- bundle install
- bundle exec rake package:frameworks

And this should build all frameworks :)

**Comment by decoyfox** [comment]
`rake aborted!
LoadError: cannot load such file -- /Users/mtannone/Downloads/Parse-SDK-iOS-OSX-master/Vendor/xctoolchain/Scripts/xctask/build_task
/Users/mtannone/Downloads/Parse-SDK-iOS-OSX-master/Rakefile:10:in `require_relative'
/Users/mtannone/Downloads/Parse-SDK-iOS-OSX-master/Rakefile:10:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
`

**Comment by decoyfox** [comment]
sorry, i don't know if this is helpful at all

**Comment by flovilmart** [comment]
Oops, forgot to tell you to fetch the submodules:

- git submodule update --init --recursive

And then the rake command again :)

**Comment by decoyfox** [comment]
`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by flovilmart** [comment]
DId you do that in the cloned folder?

**Comment by flovilmart** [comment]
@decoyfox, @airdrummingfool, @ColossalChris, @sdsanches, @nebitrams  I just tested with the built frameworks available from github, and there's no issue for me.

I'm using Xcode Version 9.0 (9A235)

My steps to reproduce:

- create new project (single view all)
- drag/drop Parse / Bolts in to the project
- Adds them to the target
- Add `import Parse` and `import Bolts` 
- build / run...

**Comment by flovilmart** [comment]
When inspecting the parse binary with file, I realized some archs are probably missing

```
build/Parse.framework/Parse: Mach-O universal binary with 2 architectures: [arm_v7k: current ar archive] [i386]
build/Parse.framework/Parse (for architecture armv7k):  current ar archive
build/Parse.framework/Parse (for architecture i386):    current ar archive
```

**Comment by flovilmart** [comment]
I've uploaded again builds for the latest release, upon download:

```
file ~/Downloads/Parse-iOS/Parse.framework/Parse
/Users/florent/Downloads/Parse-iOS/Parse.framework/Parse: Mach-O universal binary with 4 architectures: [arm_v7: current ar archive] [i386] [x86_64] [arm64]
/Users/florent/Downloads/Parse-iOS/Parse.framework/Parse (for architecture armv7):    current ar archive
/Users/florent/Downloads/Parse-iOS/Parse.framework/Parse (for architecture i386):     current ar archive
/Users/florent/Downloads/Parse-iOS/Parse.framework/Parse (for architecture x86_64):   current ar archive
/Users/florent/Downloads/Parse-iOS/Parse.framework/Parse (for architecture arm64):    current ar archive
```

**Comment by airdrummingfool** [comment]
I just re-downloaded 1.15.3, confirmed that all 4 architectures are present, and replaced `Parse.framework` and `Bolts.framework` in my project. After a clean and build, I am still getting the same `Undefined symbols for architecture x86_64:  "___llvm_profile_runtime"` error.

**Comment by airdrummingfool** [comment]
The problem appears to only be in `Parse.framework`. I can use the new version of `Bolts.framework` without issue, as long as I stick with Parse 1.15.2.

**Comment by flovilmart** [comment]
Bolts didn't change in between, I'm checking the diff for that release but I don't see anything that would affect compile flags.

Odd thing, is that @nebitrams reports the same issue for 1.15.0, which has been built the same way.

**Comment by airdrummingfool** [comment]
I tried `rake package:frameworks`, but ended up with a binary that was missing slices (just like you did):
```
[master] $ file Parse.framework/Parse 
Parse.framework/Parse: Mach-O universal binary with 2 architectures: [arm_v7: current ar archive] [arm64]
Parse.framework/Parse (for architecture armv7):	current ar archive
Parse.framework/Parse (for architecture arm64):	current ar archive
```

I also experience the issue with `1.15.0`, but not `1.15.1`.

**Comment by iosdec** [comment]
Go back to 1.14.4 .. been trying to solve this problem for hours now and just downgrading back to 1.14.4 solved it for me. Builds perfectly!

**Comment by flovilmart** [comment]
@iosdec how did you try to solve the issue?

**Comment by funnel20** [comment]
I have the same issue. These compiler errors are shown in my existing project on both Xcode 8.3.3 and 9.0 when I use Parse 1.15.3. 

When I revert back to 1.15.1 (just replace the Bolts.Framework and Parse.framework from _Parse-iOS.zip_) the project compiles without problems.
I have compared the pod spec from 1.15.1 with 1.15.3, but the target decencies didn't change.

**Comment by flovilmart** [comment]
@funnel20 are you using cocoa pods?

**Comment by funnel20** [comment]
@flovilmart No, I always use the ZIPs and manually replace the 2 framework files in my project.
First I delete the previous, then add the new to prevent merging conflicts within the framework bundles.

**Comment by flovilmart** [comment]
So can you try it on a fresh project? Perhaps we’re missin something obvious. If it doesn’t work just on an existing project but works on a new one, we’ll have more infos.

**Comment by funnel20** [comment]
@flovilmart I tried that with Xcode 8.3.3, but only with 1.15.3. It failed.
So I have to do a back-to-back test with 1.15.1 to proof that my workflow is correct. 
I'll post the results later.

**Comment by flovilmart** [comment]
I don’t have a copy of Xcode 8.3.3 around, but i’ll Try that as well, as well as rebuilding on this version.

**Comment by funnel20** [comment]
```
##############
##  TEST 1  ##
##############
```
Steps to reproduce with **1.15.1**:

1. Create new iOS project with _Single View Application_ in Xcode 8.3.3.
2. Add the _Bolts.framework_ and _Parse.framework_ from _Parse-iOS.zip_ version 1.15.1 to the Project.
3. Go to Project Settings, select target, click Build Phases and add the following binaries to _Link Binary With Libraries_:
- Bolts.framework
- Parse.framework
- AudioToolbox.framework
- CFNetwork.framework
- CoreGraphics.framework
- CoreLocation.framework
- QuartzCore.framework
- Security.framework
- SystemConfiguration.framework
- libsqlite3.tbd
- libz.tbd

4. Imported the Parse header on AppDelegate.m:
`#import <Parse/Parse.h>`

5. Add Parse init code in AppDelegate 'didFinishLaunchingWithOptions:':
```
[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"";
        configuration.server = @"";
    }]];
```
6. Build the project. **It compiles without errors.** 
(Yes, it finally crashes after launch since `applicationId` should not be nil, but that's not relevant for this issue).

```
##############
##  TEST 2  ##
##############
```
Repeat the same 6 steps with Xcode 8.3.3 and Parse **1.15.3**:
**Compilation fails with errors**:
> ___llvm_profile_runtime", referenced from:
> ___llvm_profile_runtime_user in Parse(Parse.o)
> ___llvm_profile_runtime_user in Parse(ParseClientConfiguration.o)
> ___llvm_profile_runtime_user in Parse(PFApplication.o)
> ___llvm_profile_runtime_user in Parse(PFCategoryLoader.o)
> ___llvm_profile_runtime_user in Parse(PFFileManager.o)
> ___llvm_profile_runtime_user in Parse(PFInternalUtils.o)
> ___llvm_profile_runtime_user in Parse(PFLogger.o)
> ...

```
##############
##  TEST 3  ##
##############
```
I loaded the same 2 projects in Xcode 9.0 and the one with 1.15.1 compiled, and 1.15.3 showed the same compiler errors.

```
##############
##  TEST 4  ##
##############
```
Repeated steps 1 till 6 in Xcode 9.0 for Parse 1.15.3. **It failed with the same compiler errors**.

**Comment by funnel20** [comment]
@flovilmart I hope the above 5 tests can help. Bottom line is that there seems no relation with Xcode version or whether the project is existing or freshly created.

**Comment by flovilmart** [comment]
What I don’t get is why it’s perfectly functional over here

**Comment by funnel20** [comment]
Did you repeat my tests with manually adding the frameworks and dependencies to your project?
Or did you use cocoa pods?

**Comment by flovilmart** [comment]
I'M referring to: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1159#issuecomment-332041950

**Comment by funnel20** [comment]
I can explain: as long as you don't use any Parse code (i.e. 'initializeWithConfiguration:' from my step 5) the compiler won't complain when building. It's even not necessary to add the dependencies.

**Comment by ceramicatheist** [comment]
Looking at https://clang.llvm.org/docs/SourceBasedCodeCoverage.html , this might have something to do with the code coverage feature:
If I do like that page mentions, and add a .c file to my project containing only
```
int __llvm_profile_runtime;
```
I get a clean compile and link (apart from the `-Wstrict-prototypes` warnings), and my app runs fine.

**Comment by flovilmart** [comment]
Thanks @ceramicatheist, that’s very odd indeed that in release build we’d have profiler/coverage info into those settings.

**Comment by flovilmart** [comment]
@funnel20 i confirm there's an issue there, I got it too now.

**Comment by flovilmart** [comment]
@ceramicatheist Thanks for the tip, that really helped troubleshooting, it seems that setting CLANG_ENABLE_CODE_COVERAGE = NO; I'M rebuilding with xcode9 now, and I'll be putting the prebuilt-libs here

**Comment by flovilmart** [comment]
[Parse-iOS.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1334279/Parse-iOS.zip)
[Parse-macOS.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1334281/Parse-macOS.zip)
[Parse-tvOS.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1334282/Parse-tvOS.zip)
[Parse-watchOS.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1334280/Parse-watchOS.zip)

**Comment by flovilmart** [comment]
@ceramicatheist I've also updated the releases packages, let me know if this persists.

**Comment by airdrummingfool** [comment]
The Parse-iOS.zip file attached to this issue fixed the problem for me. Thanks @flovilmart @ceramicatheist et. al!

**Comment by funnel20** [comment]
I can confirm too that the updated _Parse-iOS.zip_ resolves the issue.
My project now compiles without issues.

Thank you all.

**Comment by decoyfox** [comment]
Good work everyone. Working for me now as well.

**Comment by Stanou01260** [comment]
This issue was closed but I have had the exact same problem than you guys. After extracting the Zip ParseStarterProject-iOS.zip V1.15.3 found in the release page and compiling I had the 
```
"___llvm_profile_runtime" undefined symbol error 
```
To solve this I downloaded the Parse-iOS.zip given by @flovilmart few messages before, manually replaced both framework Bolt and Parse and it worked

**Comment by flovilmart** [comment]
@Stanou01260 I perhaps forgot to upload to the release then, let me have a look.

**Comment by Stanou01260** [comment]
Thank you @flovilmart

**Comment by Timmmm** [comment]
Guys error occurs if you pass -fprofile-instr-generate during compilation, but not during linking. The flag is required during linking so Clang knows to link with the appropriate profiling libraries.

**Comment by flovilmart** [comment]
@Timmmm do we need to do something on the repo?

**Comment by Timmmm** [comment]
Absolutely no idea - sorry! I've never used Objective C or Xcode. Actually I don't know what this project is (I was just Googling the same error and thought I would add what solved it for me).

Anyway, at a guess, you might have some profiling option in Xcode set on that you need to turn off, maybe in a sub-project? If you can, print the command lines that Xcode runs and look for `-fprofile-instr-generate` or similar. It could also be a code coverage option (that works in a similar way).

**Comment by Mamonaku** [comment]
just checked, they're all in.. thanks!
