### ISSUE TITLE
Carthage compilation failed with facebook SDK newer versions, starting from v4.41.0

### ISSUE THREAD

**Issue by bayareahank** [parse-community/Parse-SDK-iOS-OSX#1396]
Carthage build failed with latest versions of facebook SDK, starting from v4.41.0. 

Carthage version 0.32.0, Xcode 10.1. 

Cartfile: 
github "ParsePlatform/Parse-SDK-iOS-OSX" "1.17.2"

Carthage build works till v4.40.0, then failed while building scheme "ParseFacebookUtilsV4-iOS-Dynamic" in Parse.xcworkspace. The error msg complains of a header file missing: 

In file included from Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/ParseFacebookUtils/Internal/AuthenticationProvider/iOS/PFFacebookMobileAuthenticationProvider.m:10:
Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/ParseFacebookUtils/Internal/AuthenticationProvider/iOS/PFFacebookMobileAuthenticationProvider.h:12:9: fatal error: 'FBSDKLoginKit/FBSDKLoginManager.h' file not found
#import <FBSDKLoginKit/FBSDKLoginManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

From the compilation orders, I am not sure FBSDKLoginKit (and a few other Kits, like CoreKit, PlacesKit, ShareKit etc.) is still being used for Facebook SDK v4.41.0 and later, while they would show up when compiling v4.40.0, before compiling ParseFacebookUtilsV4-iOS-Dynamic.

*** Building scheme "Bolts-iOS" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Parse-iOS-Dynamic" in Parse.xcworkspace
*** Building scheme "Parse-iOS" in Parse.xcworkspace
*** Building scheme "ParseFacebookUtilsV4-iOS" in Parse.xcworkspace
*** Building scheme "ParseFacebookUtilsV4-iOS-Dynamic" in Parse.xcworkspace

**Comment by eduardbosch** [comment]
Same problem here using Xcode 10.2 10E125
I'm moving to Carthage. With CocoaPods there is no problem.

**Comment by bayareahank** [comment]
Surprisingly, after I updated to Swift 5 / Xcode 10.2 this morning, Carthage build works with latest Facebook SDK v4.42.0. I verified this both with Parse-SDK-iOS-OSX and Parse-LiveQuery. Older versions of Facebook SDK would fail instead. It looks to be a glitch on the Facebook SDK side. I am going to close on this.

**Comment by mman** [comment]
Builds fine for iOS using:

```
```

But fails to build for tvOS (not that I need it) with this error:

```
Parse-SDK-iOS-OSX/ParseFacebookUtils/ParseFacebookUtils/Internal/AuthenticationProvider/tvOS/PFFacebookDeviceAuthenticationProvider.m:18:9: fatal error: 'FBSDKTVOSKit/FBSDKDeviceLoginViewController.h' file not found
```
