### ISSUE TITLE
Error 206 after PFUser.logInWithAuthType(inBackground: "apple", 

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/Parse-SDK-iOS-OSX#1477]
I am trying to implement Sign in With Apple.  I am able to successfully authenticate the user on my iPhone 11 running iOS 13.3 using iOS API. 
Parse Server version 3.9.0. 
Parse iOS SDK  1.17.3

As part of login process, i save more information in _User for the newly created user after PFUser.logInWithAuthType(inBackground: "apple",  is executed successfully. 

I get error 206 when saving. I read somewhere that it could be related nil sessionToken. it is indeed nil after successful login. The PFUser.current().authenticated is true.

I read in many posts about keychain access but not able find entry for my app in Keychain app. is missing entry an issue? How to add it? Keychain Sharing is enabled.

I have also Facebook and email based account. These work fine.

How to fix the issue?

Things i have tried
1. Clear build
2. Clean folder
3. Delete app

Thanks
Ashish

**Comment by drdaz** [comment]
Hi Ashish

It's hard to know exactly what you're running into here without seeing your code. But I've got a working implementation of Sign in with Apple in one of my apps and haven't used the Keychain in any way that I'm aware. Keychain Sharing is disabled.

I also update my user once the loginWithAuthType background call completes. The only thing I can think of is if you don't do the update in the continueWith block (you just put the user updates and saves on the line after loginWithAuthType), then the update would fail since the user isn't authenticated yet - the background login task would execute after your updates.

**Comment by ashish-naik** [comment]
Hi Darren,

Sign in with Apple is working and i am not using keychain API anywhere. i found some posts about error 206 indicating that issue could be with nil sessionToken due to keychain issue hence i mentioned.

I tried debugging by adding a breakpoint in PFObject.m line 1449 and found sessionToken is nil even though currentuser is authenticated.
I also added a breakpoint in PFKeychainStore.m line 100 and found keychain has proper value when app launches.

Coming to updating user after login - yes i also update in continueWith block. My code is like below. have mentioned where i am getting error 206 in method saveNewUserToParse().

Could the problem be because switching to main queue and calling callback from there?

```
fileprivate func loginWith(authType: String, using idTokenString: String, userId: String, callback: @escaping  (PFUser?, NSError?) -> ()) {
    
    PFUser.register(AuthDelegate(), forAuthType: "apple")
    
    PFUser.logInWithAuthType(inBackground: "apple", authData: ["token":idTokenString, "id": userId]).continueWith { task -> Any? in
        
        if ((task.error) != nil){

            DispatchQueue.main.async {

                CommonHelper.showMessage(messageBody: "Could not login.\n Please try again.", messageType: Constants.errorMessage, presentationStyle: .top, durationInSeconds: 3)

                logger.error("Error with parse login after SIWA: \(task.error!.localizedDescription)")
                callback(nil, task.error! as NSError)
            }
            
            return task

        }
        
        let loggedInUser = task.result
            
                DispatchQueue.main.async {

                CommonHelper.showMessage(messageBody: "Log in successful", messageType: Constants.successMessage, presentationStyle: .top, durationInSeconds: 3)

                callback(loggedInUser, nil)
            }
        
        return nil
    }
}


 @available (iOS 13,*)
func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
    switch authorization.credential {
        case let credentials as ASAuthorizationAppleIDCredential:

            guard let appleIDToken = credentials.identityToken else {
                        
                 CommonHelper.showMessage(messageBody: "Encountered error during login", messageType: Constants.errorMessage, presentationStyle: .top, durationInSeconds: 5)
            
                //show login screen
                self.showLoginScreen()
            
                return
            }
            let idTokenString = String(data: appleIDToken, encoding: .utf8)

            self.loginWith(authType: "apple", using: idTokenString!, userId: appleCredentialUserId) { (loggedInUser, error) in
                                        
                if error == nil && loggedInUser != nil {
                    
                    logger.info("Login successful with loggedInUser id \(loggedInUser!.objectId!)")
                                                                    
                    // go ahead with saving details in parse
                    let nameToBeSaved: String?
                    
                    if credentials.fullName != nil {
                        
                        nameToBeSaved = (credentials.fullName?.givenName ?? "") + " " + (credentials.fullName?.familyName  ?? "")
                    } else {
                        // saved when user sign in for first time
                        nameToBeSaved = userNameFromUserDefaults
                    }

                    self.saveUserDetailsOnParse(isNewUser: loggedInUser!.isNew, user: loggedInUser! ,socialId: appleCredentialUserId, email: emailToBeSaved, name: nameToBeSaved! , profileImageURL: nil, loginProvider: "apple",  callback: { (message, error) in
                        
                        
                        if error == nil {
                            
                            //show app content
                            self.gotoHomeView()
                            
                        } else if error != nil {
                                                                                    
                            CommonHelper.showMessage(messageBody: "Enountered error. Please try again.", messageType: Constants.errorMessage, presentationStyle: .top, durationInSeconds: 0)
                            
                            logger.error("Error updating User in Parse Error Code \(error.code):\(error.localizedDescription)")

                            CommonHelper.logoutFromParse()

                            //show login view
                            self.showLoginScreen()
                            
                        }
                        
                    }) //end of self.saveUserDetailsOnParse
                    
                } else if error != nil {

                    CommonHelper.showMessage(messageBody: "Enountered error. Please try again.", messageType: Constants.errorMessage, presentationStyle: .top, durationInSeconds: 0)

                    logger.error("Couldnt login to Parse after SIWA \(error!.localizedDescription)")
                                                                    
                    self.showLoginScreen()
                    
                }//end of  if error == nil && loggedInUser != nil
                
            } //self.loginWith(authType: "apple",


        break
    }
}


   func saveUserDetailsOnParse(isNewUser: Bool, user: PFUser?, socialId: String, email: String, name: String, profileImageURL: String?, loginProvider: String, callback: @escaping (String, NSError?) -> ())  {
        
        if name != "" {
           //if email based user logged in then name will be blank so update/add only if not blank ie for social login
            PFUser.current()?["name"] = name
        }
        if profileImageURL != nil {
            
            //if email based or Apple user logged in then URL will be blank so update/add only if not blank ie for social login
            PFUser.current()?["profile_image_url"] = profileImageURL!
        }
                
        PFUser.current()?["email"] = email
        
        if isNewUser {
           //if logged in user isNew  property is true
            self.saveNewUserToParse(socialId: socialId, loginProvider: loginProvider) { (errorMessage, error) in
                
                callback(errorMessage, error)
            }

        } else {
            //save details for existing user
            PFUser.current()?.saveInBackground(block: { (successSaveUser, error) in
               
              
                if successSaveUser {
                    logger.debug("User attributes updated to Parse")
                    callback("User attributes updated to Parse", nil)
                    
                } else {
                    
                    logger.debug("Error saving current PFUser post login to parse")
                    callback("Error saving current PFUser post login to parse", error! as NSError)
                    
                }
            })
        }
        
    }

           
    func saveNewUserToParse(socialId: String?, loginProvider: String?, callback: @escaping (String, NSError?) -> ())  {
        
        PFUser.current()?["social_id"] = socialId
        PFUser.current()?["login_provider"] = loginProvider
                            
        // Setup some seed values for the newly created user
 
        PFUser.current()?.saveInBackground(block: { (successSaveUser, error) in

                //MARK: Getting error 206 here
           if successSaveUser {
                logger.debug("User attributes  updated to Parse")
                
                let userPrefs = PFObject(className:"preferences")
                
                userPrefs["user"] = PFUser.current()
                //set seed prefs
                
                userPrefs.saveInBackground(block: { (success: Bool, error: Error?) in
                    if success {
                        
                        logger.debug("User preferences created on Parse")

                        
                    } else { //error saving preferences to Parse
                        
                        logger.severe("error saving Preferences post login/signup to parse \(String(describing: error?.localizedDescription))")
                        callback("Error saving Preferences post login/signup to parse", error! as NSError)
                        
                    }
                }) //end of userPrefs.saveInBackground
                
                callback("New user's attributes saved to Parse", nil)

                
            } else {
              
                    logger.debug("Error saving current PFUser post login/signup to parse  \(error!.localizedDescription)")
                    callback("Error saving current PFUser post login/signup to parse", error! as NSError)
                    
                
            }
        })
        
    }
```

**Comment by TomWFox** [comment]
Just wondering... have you actually setup Sign in with Apple on your Parse Server config, if so can you share that just to check that is all ok?

**Comment by ashish-naik** [comment]
auth: {
   apple: {
    client_id: "my bundle id", // optional (for extra validation), use the Service ID from Apple.
  }
  }

**Comment by SaluBhayo** [comment]
@ashish-naik have you completed the setup of sign in with apple with Parse?

**Comment by TomWFox** [comment]
@ashish-naik  have you actually got a service id in the client id field?

**Comment by ashish-naik** [comment]
@SaluBhayo  What else i need to setup apart from auth section in index.js?

@TomWFox  No i had tried service id first but login didnt work so changed to bundle id. I have not done domain verification though in Apple service id configuration.  Dont know if it is needed for iOS app to work.

**Comment by SaluBhayo** [comment]
@ashish-naik I'm also looking into that issue session token expires after some times but apple doesn't give token expiration time, I'm hitting sign in with apple every time on splash screen for the time being until issue get resolved

**Comment by TomWFox** [comment]
@ashish-naik it may be unrelated but if you don’t have a valid service ID to put under the client ID field I would remove it

**Comment by ashish-naik** [comment]
But this says that client Id tag is mandatory even if kept blank.

https://github.com/parse-community/parse-server/issues/5632#issuecomment-531028259

**Comment by TomWFox** [comment]
Ah ok, looks like the docs might need an update then :)

**Comment by ashish-naik** [comment]
So i first removed my bundle id and tested. Login to parse failed.

Then i commented client id line and tested. Got error 206.

What else i can try?

**Comment by TomWFox** [comment]
Can you see any auth data being populated in the user class on your server?

**Comment by ashish-naik** [comment]
authData and username are updated. 

AuthDats is set to value i pass with login call.
Username is a random string.

**Comment by ashish-naik** [comment]
i tried setting service id as client and got below error. If i understand correctly, server expects service id which i have set.

 error: Parse error: jwt aud parameter does not include this client - is: _bundleid_ | expected: _serviceid_ {"code":101,"stack":"Error: jwt aud parameter does not include this client - is: __bundleid__ | expected: __serviceid_\n_    at verifyIdToken (/app/node_modules/parse-server/lib/Adapters/Auth/apple.js:59:11)

**Comment by ashish-naik** [comment]
Hi Tom, any hint for me?

**Comment by ashish-naik** [comment]
I did some debugging in iOS SDK and below are some screenshots.

Second screenshot shows that sessionToken key is missing from result in _mergeFromServerWithResult

Do these give any hint?


<img width="1036" alt="nil sessionToken debug 1" src="https://user-images.githubusercontent.com/4936420/72203287-871cca00-348f-11ea-94f9-b9c4719363ec.png">

<img width="1045" alt="nil sessionToken debug 2" src="https://user-images.githubusercontent.com/4936420/72203290-9734a980-348f-11ea-974d-2a0aa7b7e05b.png">

**Comment by ashish-naik** [comment]
i tried a bit different approach of creating an anonymous user first  and then try linking it as suggested in https://github.com/parse-community/parse-server/issues/5632#issuecomment-531016393

But still getting error 206 !!

**Comment by ashish-naik** [comment]
I tried with back4app and my code worked so i guess it rules out issue in my code?

**Comment by drdaz** [comment]
@ashish-naik Yeah, that does strongly suggest that it's your server setup there's something wrong with.

**Comment by ashish-naik** [comment]
I upgraded to 3.10.0.

Need one help. When i updated to 3.9.0, i made changes to package.json. I am taking parse-example as base. Does this look okay? I frankly don't know what all those packages are for and what version should be at but i tried to see latest parse server code and adopted from there :)


```
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.17.x",
    "kerberos": "~0.0.x",
    "parse": "~2.11.*",
    "parse-server": "3.10.0",
    "cors": "*",
    "moment":"^2.14.1",
    "underscore": "*",
    "npm": "5.7.1"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": "9.x"
  },
  "devDependencies": {
    "babel-cli": "^6.7.7"
  }
}
```

**Comment by ashish-naik** [comment]
@drdaz I havent changed anything other than package.json as above. Is anything wrong with it?


I also tried to change package.json to one supplied with parse-server-example project with "parse-server": "3.10.0" but server crashed with Error: Cannot find module 'underscore'

**Comment by ashish-naik** [comment]
@drdaz i thought a fresh Parse Server could solve the problem so I created another app in Heroku with Parse Server 3.1.0 using below package.json, pointed to existing database and pointed my app to new server.

Still getting the error !! What do i now?

```
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "3.10.0",
    "underscore":"*"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

```

**Comment by ashish-naik** [comment]
@AlexmReynolds I am really struck with this. I guess your setup is working fine. i tried everything that i could. Login with email and facebook are working fine.

Could you please help? Do check my comments above to see what all i have tried.

My current parse server is updated with below package.json. My index.js has below auth section. 

```
auth: {
    apple: {   
      client_id: process.env.IOS_BUNDLE_ID
    }
  }
```

```
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ashish-naik/parse-server.git"
  },
  "license": "MIT",
  "dependencies": {
    "express": ">4.11.x",
    "kerberos": ">0.0.x",
    "parse": ">1.8.0",
    "parse-server": "3.10.0",
    "underscore":"*"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

```

**Comment by drdaz** [comment]
@ashish-naik This is outside of the scope of the Parse iOS SDK issue tracker. That the SDK and your code work shows there is no issue in the iOS SDK here. You'll probably have better luck getting useful help somewhere like StackOverflow or the Parse community forum.

I can take a look at your project, but it would be in a professional context; let me know.

**Comment by ashish-naik** [comment]
Hi Darren,

I posted on SO and parse Community but didnt get response so posted under parse-server yesterday.

In meantime, i installed Parser server locally and it worked. 
I even created new app on heroku to test against fresh installation but it didn't work. Now i wonder whether Heroku is causing issue but dont know how to debug that.

You said this is not iOS SDK issue but i am still trying to debug. I noticed that login is being called nil `sessionToken`. Does this sound correct?

```
+ (instancetype)serviceLoginUserCommandWithAuthenticationType:(NSString *)authenticationType
                                           authenticationData:(NSDictionary *)authenticationData
                                             revocableSession:(BOOL)revocableSessionEnabled
                                                        error:(NSError **)error {
    NSDictionary *parameters = @{ @"authData" : @{ authenticationType : authenticationData } };
    return [self serviceLoginUserCommandWithParameters:parameters
                                      revocableSession:revocableSessionEnabled
                                          sessionToken:nil
                                                 error:error];
}
```
I am not able to debug any further.

Appreciate your help. What will you need to investigate?

**Comment by drdaz** [comment]
Hi Ashish

Is there some way I can contact you directly? Email perhaps?

> I noticed that login is being called nil sessionToken. Does this sound correct?

Facebook and Twitter logins use this codepath, and the nil doesn't seem to be a problem for them. So I'm pretty sure that's fine 🙂

**Comment by ashish-naik** [comment]
My id - naik.ashu@gmail.com

**Comment by drdaz** [comment]
@ashish-naik got it. I deleted it from here to avoid you getting spammed. I'll mail you soon.

**Comment by ashish-naik** [comment]
Hi Darren,

i did some more digging. Added some logging statements in RestWrite.js as below .

tested on parse server 4.2.0 installed from my private repo in Heroku.

Can you please have a look and see what it tells?

```
RestWrite.prototype.handleAuthData = function(authData) {
  let results;
  return this.findUsersWithAuthData(authData).then(async r => {
    results = this.filteredObjectsByACL(r);

    logger.info('MESSAGE - In RestWrite.prototype.handleAuthData - Results is' + results)

    if (results.length == 1) {
      logger.info('MESSAGE - In RestWrite.prototype.handleAuthData - Results.length = 1')
      this.storage['authProvider'] = Object.keys(authData).join(',');

      logger.info('MESSAGE - In RestWrite.prototype.handleAuthData - storage authProvider = ' + this.storage['authProvider'])

      const userResult = results[0];
```

```
RestWrite.prototype.createSessionTokenIfNeeded = function() {

logger.info('Message - RestWrite - in createSessionTokenIfNeeded - For class - ' + this.className)
  if (this.className !== '_User') {
    return;
  }
  // Don't generate session for updating user (this.query is set) unless authData exists
  if (this.query && !this.data.authData) {
    return;
  }
  logger.info('Message - RestWrite - in createSessionTokenIfNeeded -Not update call - going ahed')

  // Don't generate new sessionToken if linking via sessionToken
  if (this.auth.user && this.data.authData) {
    return;
  }
  logger.info('Message - RestWrite - in createSessionTokenIfNeeded - not linking so go ahead ' )

  if (
    !this.storage['authProvider'] && // signup call, with
    this.config.preventLoginWithUnverifiedEmail && // no login without verification
    this.config.verifyUserEmails
  ) {
    // verification is on
    logger.info('Message - RestWrite - in createSessionTokenIfNeeded - returning as no auth provider, preventLoginWihoutEmail, verifyEmail')   
    logger.info('Message - RestWrite - in createSessionTokenIfNeeded - authProvider = ' + this.storage['authProvider'] + ' preventLoginWihoutEmail = ' + this.config.preventLoginWithUnverifiedEmail + ' verifyUserEmails = ' + this.config.verifyUserEmails)
    return; // do not create the session token in that case!
  }
  logger.info('Message - RestWrite - in createSessionTokenIfNeeded - before calling - return this.createSessionToken()' )

  return this.createSessionToken();
};

RestWrite.prototype.createSessionToken = async function() {
  // cloud installationId from Cloud Code,
  // never create session tokens from there.
logger.info('Message - RestWrite - in RestWrite.prototype.createSessionToken = async function()')
  if (this.auth.installationId && this.auth.installationId === 'cloud') {
    return;
  }

  const { sessionData, createSession } = Auth.createSession(this.config, {
    userId: this.objectId(),
    createdWith: {
      action: this.storage['authProvider'] ? 'login' : 'signup',
      authProvider: this.storage['authProvider'] || 'password',
    },
    installationId: this.auth.installationId,
  });

  if (this.response && this.response.response) {
    this.response.response.sessionToken = sessionData.sessionToken;
  }
logger.info('Message - RestWrite - sessionData')
  return createSession();
};
```

Output in logs
```
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - Results is
app/web.1 info: Message - RestWrite - in createSessionTokenIfNeeded - For class - _User
app/web.1 info: Message - RestWrite - in createSessionTokenIfNeeded -Not update call - going ahed
app/web.1 info: Message - RestWrite - in createSessionTokenIfNeeded - not linking so go ahead 
app/web.1 info: Message - RestWrite - in createSessionTokenIfNeeded - returning as no auth provider, preventLoginWihoutEmail, verifyEmail
app/web.1 info: Message - RestWrite - in createSessionTokenIfNeeded - authProvider = undefined preventLoginWihoutEmail = true verifyUserEmails = true
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - Results is[object Object]
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - Results.length = 1
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - storage authProvider = apple
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - Results is[object Object]
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - Results.length = 1
app/web.1 info: MESSAGE - In RestWrite.prototype.handleAuthData - storage authProvider = apple
```

What i noticed is that in if statement on line 920 is evaluated to true hence `return createSession();` isnt called.
and this.storage['authProvider'] is set after call to createSessionTokenIfNeeded so authProvider value isnt set. Am i right?

I tried sign up multiple times and it worked once randomly but that is before i added all the logger statements so dont have logs. 
By the way, even Facebook login is failing with same way, I had created another issue earlier [here](https://github.com/parse-community/parse-server/issues/6511)
I just checked that the log shows same sequence of statements for facebook login also.

is this caused by something wrong being passed from iOS client code or issue at parse server end or heroku?

My package.json is 

```
{
  "name": "YOVL",
  "version": "1.0.0",
  "description": "yovl server based on example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ashish-naik/yovl-parse-server"
    
  },
  "license": "MIT",
  "dependencies": {
    "express": "4.17.1",
    "underscore":"*",
    "parse": "2.12.0",
    "cryptoutils":"*",
    "cors":"*",
    "parse-server": "git+https://token@github.com/ashish-naik/parse-server.git#master"
    
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">= 8",
    "npm": ">= 5.7.1"
  }
}
```

heroku build log excerpt 

```
-----> Installing binaries
       engines.node (package.json):  >= 8
       engines.npm (package.json):   >= 5.7.1
       
       Resolving node version >= 8...
       Downloading and installing node 13.11.0...
       Bootstrapping npm >= 5.7.1 (replacing 6.13.7)...
       npm >= 5.7.1 installed

```
Ashish
